In [1]:
import numpy as np
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.transpose()

a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Импортируем библиотеку создаем под матрицу 5х2 список

In [2]:
print(a.shape, a, sep='\n')


(5, 2)
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]


смотрим размерность а так же значения

In [3]:
mean_a = a[:,0].mean(), a[:,1].mean()
print(mean_a)

(2.0, 8.4)


вычисляем среднее методом mean()

In [4]:
add = [[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]
add = sum(add[0]) / len(add[0]), sum(add[1]) / len(add[1])
add

(2.0, 8.4)

проверяем средствами питона среднее у двух столбцов = верно)

# задание 2

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

# задание 3

In [6]:
a_centered_sp = a_centered[:, 0] @ a_centered[:, 1]
a_centered_sp / (a_centered.size - 1)


0.8888888888888888

# задание 4

In [7]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])